name: mobx_flutter
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: 0.13.5
  flutter_slidable: ^2.0.0
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.0.7+3



  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

